# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK0/SYSCLK0.xci
# IP: The module: 'SYSCLK0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK0/SYSCLK0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK0/SYSCLK0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK0/SYSCLK0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK0/SYSCLK0.xci
# IP: The module: 'SYSCLK0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK0/SYSCLK0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK0/SYSCLK0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK0/SYSCLK0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
