@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Apr 14 16:15:27 +0900 2023
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim ADC_SiTCP_RAW_TB_behav -key {Behavioral:sim_1:Functional:ADC_SiTCP_RAW_TB} -tclbatch ADC_SiTCP_RAW_TB.tcl -view C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sim_1/imports/PAPILLON_v4raw/ADC_SiTCP_RAW_TB_behav.wcfg -log simulate.log"
call xsim  ADC_SiTCP_RAW_TB_behav -key {Behavioral:sim_1:Functional:ADC_SiTCP_RAW_TB} -tclbatch ADC_SiTCP_RAW_TB.tcl -view C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sim_1/imports/PAPILLON_v4raw/ADC_SiTCP_RAW_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
