# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/seida/Desktop/PAPILLON_FW/PAPILLON_v3/PAPILLON_v3.srcs/sources_1/ip/mem_8_4K/mem_8_4K.xci
# IP: The module: 'mem_8_4K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/seida/Desktop/PAPILLON_FW/PAPILLON_v3/PAPILLON_v3.srcs/sources_1/ip/mem_8_4K/mem_8_4K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_8_4K'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/seida/Desktop/PAPILLON_FW/PAPILLON_v3/PAPILLON_v3.srcs/sources_1/ip/mem_8_4K/mem_8_4K.xci
# IP: The module: 'mem_8_4K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/seida/Desktop/PAPILLON_FW/PAPILLON_v3/PAPILLON_v3.srcs/sources_1/ip/mem_8_4K/mem_8_4K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_8_4K'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
