# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2.xci
# IP: The module: 'SYSCLK2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2.xci
# IP: The module: 'SYSCLK2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kensh/Desktop/FPGA/PAPILLON/PAPILLON_v3s/PAPILLON_v3s.srcs/sources_1/ip/SYSCLK2/SYSCLK2_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSCLK2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
