# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.cache/wt [current_project]
set_property parent.project_path C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/new/ADC_IF.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/sources_1/new/ADC_INT.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/sources_1/imports/src/ADC_SiTCP_RAW.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/src/ADC_SiTCP_RING.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/src/AD_ADC_SPI.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/firmware/LEDSet.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/src/LOC_REG.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/new/SIF_IF2_TEST.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/new/SIF_IF2_selectio_wiz_TEST.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/src/SiTCP_XC7A_32K_BBT_V80.V
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/src/TIMER.v
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/src/WRAP_SiTCP_GMII_XC7A_32K.V
  C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/src/ADC_SiTCP_V20.v
}
read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK0/SYSCLK0.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK0/SYSCLK0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK0/SYSCLK0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK0/SYSCLK0_ooc.xdc]

read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK2/SYSCLK2.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK2/SYSCLK2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK2/SYSCLK2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK2/SYSCLK2_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/SYSCLK2/SYSCLK2_ooc.xdc]

read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc]

read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/mem_8_4K/mem_8_4K.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/mem_8_4K/mem_8_4K_ooc.xdc]

read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/mult_gen_1/mult_gen_1_ooc.xdc]

read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/divider/divider.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/divider/divider_ooc.xdc]

read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/mult_gen_2/mult_gen_2.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/mult_gen_2/mult_gen_2_ooc.xdc]

read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/cordic_0/cordic_0_ooc.xdc]

read_ip -quiet C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]

read_edif C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/sources_1/imports/sources_1/imports/src/SiTCP_XC7A_32K_BBT_V80.ngc
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/constrs_1/imports/papillon_24ch/constrs_1.xdc
set_property used_in_implementation false [get_files C:/Users/81802/Desktop/PAPILLON_FW/PAPILLON_v2023/PAPILLON_v2023.srcs/constrs_1/imports/papillon_24ch/constrs_1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ADC_SiTCP_V20 -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ADC_SiTCP_V20.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ADC_SiTCP_V20_utilization_synth.rpt -pb ADC_SiTCP_V20_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
